---
- name: Install NGINX
  ansible.builtin.yum:
    name: nginx
    state: present

- name: Enable & Start NGINX
  ansible.builtin.service:
    name: nginx
    enabled: yes
    state: started

- name: Deploy PHP index file
  ansible.builtin.template:
    src: ../../../app/src/index.php
    dest: /var/www/html/index.php
    owner: nginx
    group: nginx
    mode: "0644"
  